[package]
name = "gettext-macros"
version = "0.1.0"
authors = ["Baptiste Gelez <baptiste@gelez.xyz>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
gettext-utils = { path = "gettext-utils" }
gettext = "0.3"

[workspace]
members = ["gettext-utils"]